language: python

env:
  - TOXENV=py26-mysql
  - TOXENV=py27-mysql
  - TOXENV=py26-postgres
  - TOXENV=py27-postgres
  - TOXENV=py26-sqlite
  - TOXENV=py27-sqlite
  - TOXENV=py34-sqlite
  - TOXENV=py27-pyflakes
  - TOXENV=py34-pyflakes

install: pip install tox

matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=py34-sqlite
    - env: TOXENV=py27-pyflakes
    - env: TOXENV=py34-pyflakes

script: tox -e ${TOXENV}
