language: python
python:
  - "2.6"
  - "2.7"

branches:
  only:
    - master

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

install:
  - if [[ $DB == mysql ]]; then pip install --use-mirrors mysql-python; fi;
  - if [[ $DB == postgres ]]; then pip install --use-mirrors psycopg2; fi;

before_script:
  - if [[ $DB == mysql ]]; then mysql -e 'create database sqlobject_test;'; fi;
  - if [[ $DB == postgres ]]; then psql -c 'create database sqlobject_test;' -U postgres; fi;

script:
  - cd sqlobject
  - if [[ $DB == mysql ]]; then /usr/bin/py.test -D mysql://root:@localhost/sqlobject_test; fi
  - if [[ $DB == postgres ]]; then /usr/bin/py.test -D postgres://postgres:@localhost/sqlobject_test; fi
  - if [[ $DB == sqlite ]]; then /usr/bin/py.test -D sqlite:///tmp/sqlobject_test.sqdb; fi
