# Prefer docker container with setuid/sudo
sudo: required

language: python

cache: pip

addons:
  apt:
    packages:
      - python-egenix-mxdatetime
      - firebird2.5-super

before_install:
  # Start the firebird database server.
  # We use firebird-super, so there's none of the inetd configuration
  # required by firebird-classic.
  # We also create a test user for the firebird test and
  # create a script that can be fed into isql-fb
  # to create the test database.
  - if [[ $TOXENV = *firebird* ]]; then
      sudo sed -i /etc/default/firebird2.5 -e 's/=no/=yes/' &&
      sudo /etc/init.d/firebird2.5-super start && sleep 5 &&
      sudo touch /var/lib/firebird/create_test_db &&
      sudo chmod 666 /var/lib/firebird/create_test_db &&
      echo "CREATE DATABASE 'localhost:/tmp/test.fdb';" > /var/lib/firebird/create_test_db &&
      sudo chmod 644 /var/lib/firebird/create_test_db &&
      sudo gsec -user sysdba -pass masterkey -add test -pw test;
    fi

env:
  - TOXENV=py27-firebird-fdb
  - TOXENV=py34-firebird-fdb
  - TOXENV=py35-firebird-fdb
  - TOXENV=py27-firebirdsql
  - TOXENV=py34-firebirdsql
  - TOXENV=py35-firebirdsql

install: pip install tox

matrix:
  allow_failures:
    - env: TOXENV=py27-firebird-fdb
    - env: TOXENV=py34-firebird-fdb
    - env: TOXENV=py35-firebird-fdb
    - env: TOXENV=py27-firebirdsql
    - env: TOXENV=py34-firebirdsql
    - env: TOXENV=py35-firebirdsql
  fast_finish: true

script: tox -e ${TOXENV}
