# Prefer docker container with setuid/sudo
sudo: required

language: python

cache: pip

addons:
  apt:
    packages:
      - python-egenix-mxdatetime
      - python-mysqldb
      - python-psycopg2
      - python3-psycopg2
      - firebird2.5-super
  postgresql: "9.4"

# Start the firebird database server
# We use firebird-super, so there's none of the inetd configuration required by firebird-classic
# We also create a test user for the firebird test and create a script that can be fed into isql-fb to create the test database
before_install:
   - sudo sed -i /etc/default/firebird2.5 -e 's/=no/=yes/' && sudo /etc/init.d/firebird2.5-super start
   - sudo touch /var/lib/firebird/create_test_db && sudo chmod 666 /var/lib/firebird/create_test_db && echo "CREATE DATABASE 'localhost:/tmp/test.fdb';" > /var/lib/firebird/create_test_db && sudo chmod 644 /var/lib/firebird/create_test_db
   - sudo gsec -user sysdba -pass masterkey -add test -pw test

env:
  - TOXENV=py26-mysqldb
  - TOXENV=py27-mysqldb
  - TOXENV=py34-mysqlclient
  - TOXENV=py35-mysqlclient
  - TOXENV=py26-mysql-connector
  - TOXENV=py27-mysql-connector
  - TOXENV=py34-mysql-connector
  - TOXENV=py35-mysql-connector
  - TOXENV=py26-oursql
  - TOXENV=py27-oursql
  - TOXENV=py26-pymysql
  - TOXENV=py27-pymysql
  - TOXENV=py34-pymysql
  - TOXENV=py35-pymysql
  - TOXENV=py26-psycopg
  - TOXENV=py27-psycopg
  - TOXENV=py34-psycopg
  - TOXENV=py35-psycopg
  - TOXENV=py26-pygresql
  - TOXENV=py27-pygresql
  - TOXENV=py34-pygresql
  - TOXENV=py35-pygresql
  - TOXENV=py34-pypostgresql
  - TOXENV=py35-pypostgresql
  - TOXENV=py26-pg8000
  - TOXENV=py27-pg8000
  - TOXENV=py34-pg8000
  - TOXENV=py35-pg8000
  - TOXENV=py26-sqlite
  - TOXENV=py27-sqlite
  - TOXENV=py34-sqlite
  - TOXENV=py35-sqlite
  - TOXENV=py27-flake8
  - TOXENV=py34-flake8
  - TOXENV=py27-fdb
  - TOXENV=py34-fdb
  - TOXENV=py35-fdb
  - TOXENV=py27-firebirdsql
  - TOXENV=py34-firebirdsql
  - TOXENV=py35-firebirdsql

install: pip install tox coveralls codecov

matrix:
  allow_failures:
    - env: TOXENV=py26-pygresql
    - env: TOXENV=py27-pygresql
    - env: TOXENV=py34-pygresql
    - env: TOXENV=py35-pygresql
    - env: TOXENV=py34-pypostgresql
    - env: TOXENV=py35-pypostgresql
    - env: TOXENV=py26-pg8000
    - env: TOXENV=py27-pg8000
    - env: TOXENV=py34-pg8000
    - env: TOXENV=py35-pg8000
    - env: TOXENV=py27-fdb
    - env: TOXENV=py34-fdb
    - env: TOXENV=py35-fdb
  fast_finish: true

script: tox -e ${TOXENV}

after_success:
    - cd sqlobject
    - coveralls
    - codecov
