# Install SQLObject on windows and test against MS SQL server and postgres
# Heavily inspired by Oliver Grisel's appveyor-demo (https://github.com/ogrisel/python-appveyor-demo)
# and Michael Sverdlik's appveyor-utils (https://github.com/cloudify-cosmo/appveyor-utils)
version: 3.2.{build}

# Match travis
clone_depth: 50

services:
   - mssql2014
   - postgresql

environment:
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"

  matrix:
    # from https://www.appveyor.com/docs/installed-software/#python
    - PYTHON: "C:\\Python27"
      db: mssql2014
      TOX_ENV: "pywin27-mssql"
    - PYTHON: "C:\\Python27"
      db: postgresql
      TOX_ENV: "pywin27-postgres"
    #- PYTHON: "C:\\Python27-x64"
    #  db: mssql2014
    #- PYTHON: "C:\\Python27-x64"
    #  db: postgresql
    - PYTHON: "C:\\Python34"
      db: mssql2014
      TOX_ENV: "pywin34-mssql"
    - PYTHON: "C:\\Python34"
      db: postgresql
      TOX_ENV: "pywin34-postgres"
    #- PYTHON: "C:\\Python34-x64"
    #  db: mssql2014
    #- PYTHON: "C:\\Python34-x64"
    #  db: postgresql
    #- PYTHON: "C:\\Python35"
    #  db: mssql2014
    #- PYTHON: "C:\\Python35"
    #  db: postgresql
    #- PYTHON: "C:\\Python35-x64"
    #  db: mssql2014
    #- PYTHON: "C:\\Python35-x64"
    #  db: postgresql
    #- PYTHON: "C:\\Python36"
    #  db: mssql2014
    #- PYTHON: "C:\\Python36"
    #  db: postgresql
    #- PYTHON: "C:\\Python36-x64"
    #  db: mssql2014
    #- PYTHON: "C:\\Python36-x64"
    #  db: postgresql


install:
   # Ensure we use the right python version
   - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\Program Files\\PostgreSQL\\9.5\\bin\\;%PATH%"
   - "python --version"
   - "pip install -r requirements.txt"
   - "pip install tox"
   - "pip install psycopg2"
   - "echo %PGPASSWORD%"

# Not a C project, so no build step
build: false

test_script:
   - "tox -e %TOX_ENV%"
